export const SKILLS_OPTIONS = [
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "TypeScript",
  "JavaScript",
  "HTML/CSS",
  "Tailwind CSS",
  "Node.js",
  "Express",
  "Python",
  "Django",
  "Flask",
  "Java",
  "Spring Boot",
  "C++",
  "C#",
  ".NET",
  "Go",
  "Rust",
  "Ruby",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Firebase",
  "GraphQL",
  "REST APIs",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "Linux",
  "Git",
  "CI/CD",
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Photoshop",
  "Illustrator",
  "Motion Graphics",
  "Brand Design",
  "Machine Learning",
  "Deep Learning",
  "Data Analysis",
  "Pandas",
  "NumPy",
  "TensorFlow",
  "PyTorch",
  "NLP",
  "Computer Vision",
  "Android",
  "iOS",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "Content Writing",
  "Copywriting",
  "Technical Writing",
  "SEO",
  "Marketing Strategy",
  "Social Media",
  "Video Editing",
  "Public Speaking",
  "Project Management",
] as const;

export const MAX_SKILLS = 6;
